---
- name: Launch ec2 instance
  sudo: false
  local_action: 
    module: ec2
    key_name: "{{ ec2_launch_keyname }}"
    aws_access_key: "{{ ec2_launch_aws_access_key }}"
    aws_secret_key: "{{ ec2_launch_aws_secret_key }}"
    instance_type: "{{ ec2_launch_instance_type }}"
    instance_tags: "{{ ec2_launch_tags }}"
    region: "{{ ec2_launch_region }}"
    group: "{{ ec2_launch_security_group }}"
    image: "{{ ec2_launch_image_id }}"
    state: present
    wait: yes
    wait_timeout: "{{ ec2_launch_wait_timeout }}"
  register: ec2_launch
  tags: ec2_launch

- name: set instance var
  sudo: false
  set_fact: ec2_dns={{ item.public_dns_name }}
  with_items: ec2_launch.instances

- name: display ec2 info
  debug: var=ec2_dns

- name: add ec2 instance to group
  sudo: false
  add_host: name=ec2-user@{{ ec2_dns }}
            groups=ec2
  tags: ec2_launch

- name: wait for ready
  sudo: false
  wait_for: host={{ ec2_dns }}
            port=22
            delay=20
            timeout=600
            state=started
  tags: ec2_launch
